spring:
  #  datasource:
  #    password: pw
  #    username: user
  #    url: jdbc:postgresql://localhost:5432/jdbc
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  #  jpa:
  #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo
  h2:
    console:
      enabled: true